### ISSUE TITLE
How to use Persistence with this library?

### ISSUE THREAD

**Issue by avencat** [antoniopresto/react-native-local-mongodb#10]
Hi and first, thank you for this great library!

I have been using it since this morning but I realized something, when I closed my app and came back after, the data that were in my database where not there anymore!

However, I used a persistent database. So I managed to re-read the whole documentation of the README.md and I still don't understand what am I doing wrong…

I paste you a sample of my code interacting with your library here:
```javascript
import Datastore from 'react-native-local-mongodb';

export default class DataBaseUsageExample extends Component {

  constructor(props) {
    super(props);

    this.db =  new Datastore({ filename: 'database_usage_example_database' });

    this.db.loadDatabase(function (err) {
      if (err) {
        console.log(err);
      }
    });
  }

  componentDidMount() {
    this.db.find({}, (err, docs) => {

      if (!err)
        console.log('1', docs);
      else
        console.log(err);

    });

    this.fetchData();
  }

  fetchData() {

    const url = 'http://localhost:8888/fetchdata'

    fetch(url, {
          method: "GET",
          headers: {
            'Accept': 'application/json'
          }

        }).then((response) => {

          return response.json();

        }).then((datas) => {

          if (datas.success) {

            this.db.remove({}, {multi: true}, (err) => {
              if (err) {
                Alert.alert(err);
              }
            });

            this.db.insert(this.state.currentCalendarData, (err) => {
              if (err) {
                Alert.alert(err);
              }
            });

            this.db.find({}, (err, docs) => {

              if (!err)
                console.log('2', docs);
              else
                console.log(err);

            });

          } else {

            Alert.alert('Error', 'code : ' + datas.code);

          }

        }).catch(err => {

          Alert.alert('Erreur', '', [
            {text: 'OK', onPress: () => this.setState({loading: false, refreshing: false})}
          ]);

        });
  }
}
```

So, when I launch that code, I get the following:

```
1 []
2 [ { id: 1,
       …},
    { id: 2,
       …},
    { id: 3,
       …},
    { id: 4,
       …},
    { id: 5,
       …} ]
```

And if I reload the app, I still get the same result for my logs.

Can you tell me what am I doing wrong please ?

R.N 0.44
Node v6.9.4
Tested on iPhone 6 simulator

**Comment by avencat** [comment]
I managed to save the data manually with `this.db.persistence.compactDatafile();` but shouldn't the data be saved automatically? (I waited 1 minute without refreshing the data and it still didn't save)

**Comment by antoniopresto** [comment]
Hello, thanks.
I'll test this scenario and see if anything is wrong. It should be saved automatically in [asyncStorage]( https://facebook.github.io/react-native/docs/asyncstorage.html).

**Comment by antoniopresto** [comment]
Try to use autoload and remember that db creation is asynchronous

```js
var Datastore = require('react-native-local-mongodb');
var db = new Datastore({ filename: 'DB_INFO', autoload: true });

**Comment by avencat** [comment]
I tried with autoload but it didn't fix my issue… 😕 I have to use
```javascript
this.db.persistence.compactDatafile();
```
to be able to save data. 😞

But since I managed to save my data, I know now what to do in order to save but it seems like this is an issue since I can't get the automatic save to work… 😕
