### ISSUE TITLE
AsyncStorage Couldn't read row 0, col 0 from CursorWindow

### ISSUE THREAD

**Issue by nachofregeiro** [antoniopresto/react-native-local-mongodb#13]
On Android, trying to write large files to the AsyncStorage throws the following error:

AsyncStorage Couldn't read row 0, col 0 from CursorWindow.

Is it possible to change the default storage, for example to be able to use react-native-safe-async-storage?

**Comment by antoniopresto** [comment]
> On iOS, AsyncStorage is backed by native code that stores small values in a serialized dictionary and larger values in separate files. On Android, AsyncStorage will use either RocksDB or SQLite based on what is available.

could you open a issue in AsyncStorage?

**Comment by silvafacundo** [comment]
Is there any solution for this?
