### ISSUE TITLE
Encryption and decryption of data example

### ISSUE THREAD

**Issue by ashrithks** [antoniopresto/react-native-local-mongodb#14]
Hi,
can you provide example for read/write data with encrypt/decrypt

@reyalpsirc @WaffleStudios @antoniopresto

**Comment by reyalpsirc** [comment]
@ashrithks Sorry, I’m no longer using this neither mongodb on react native atm.

**Comment by antoniopresto** [comment]
I think it is not safe to encrypt on the device. Can you detail it more?

**Comment by ashrithks** [comment]
Hi , I got the example ,
gist: https://gist.github.com/bllohar/28ee29b3304d8bf6dbc11d1b16b00130
