### ISSUE TITLE
where to find filename: <FileName> used while creating db ref

### ISSUE THREAD

**Issue by nmkulkarni007** [antoniopresto/react-native-local-mongodb#15]
var Datastore = require('react-native-local-mongodb');

export default db = new Datastore({ filename: './asyncStorageKey', autoload: true });

i am trying to export the file onto Server mongodb instance periodically...

**Comment by antoniopresto** [comment]
filename will by your key in asyncStorage

**Comment by antoniopresto** [comment]
This is a wrapper for NeDB, that uses AsyncStorage instead of a file, filename will be the key in asyncStorage
