### ISSUE TITLE
Can we create a wrapper to use localStorage for web and AsyncStorage for mobile? 

### ISSUE THREAD

**Issue by bala-compassites** [antoniopresto/react-native-local-mongodb#19]
I am working in react-native-web project. I have already used this storage in react-native. I tried to assign **localstorage to storage property in datastore**. But there is no changes. Can we create a wrapper to use localStorage for web and AsyncStorage for mobile like **react-native-storage**?

```
var Datastore = require('react-native-local-mongodb') , 
db = new Datastore({ filename: 'asyncStorageKey', storage: window.localStorage })
```
 Any idea would be much appreciated. Thank you!

**Comment by antoniopresto** [comment]
Can you use NeDB package directly?

**Comment by antoniopresto** [comment]
Nice idea, I'll try to fix it.

**Comment by Balasnest** [comment]
Its storing in web localStorage also. I haven't specify localStorage anywhere. But its working. Let me check it out completely.

![image](https://user-images.githubusercontent.com/6050520/36295533-2b8240c0-130e-11e8-8af8-d1db6a273246.png)

```
db = new Datastore({
            filename: 'sampleDBFile',
            autoload: true,
        });
```

![image](https://user-images.githubusercontent.com/6050520/36295370-3dc9720e-130d-11e8-976f-7cc783bf0fab.png)
