### ISSUE TITLE
Remove does not work after update

### ISSUE THREAD

**Issue by hkerkhoff** [antoniopresto/react-native-local-mongodb#20]
In the new Version the remove with the 'old' syntax does not work:

```
db.remove({ system: 'solar' }, { multi: true }, function (err, numRemoved) {
  // numRemoved = 3
  // All planets from the solar system were removed
});
```

instead using

```
db.remove({ system: 'solar' }, { multi: true })
  .then(fn)
  .catch(fnErr)
```
works.
Should at least be noted in the documentation?

**Comment by antoniopresto** [comment]
[fixed](https://github.com/antoniopresto/react-native-local-mongodb/commit/dbd04b8f8188a6f9cbcaa5770f7cd5e87dd8499d) in react-native-local-mongodb@1.9.1 

Can you take a look if it solved your case?
