### ISSUE TITLE
findOne does not resolve the promise if document does not exist

### ISSUE THREAD

**Issue by nachofregeiro** [antoniopresto/react-native-local-mongodb#21]

**Comment by antoniopresto** [comment]
[fixed](https://github.com/antoniopresto/react-native-local-mongodb/commit/dbd04b8f8188a6f9cbcaa5770f7cd5e87dd8499d) in react-native-local-mongodb@1.9.1 

Can you take a look if it solved your case?

**Comment by nachofregeiro** [comment]
It is working, thanks for your quick response.
