### ISSUE TITLE
Is automaticlly save on AsyncStorage ?

### ISSUE THREAD

**Issue by huythoawedding** [antoniopresto/react-native-local-mongodb#27]
hi @antoniopresto,

import Datastore from 'react-native-local-mongodb';

var db = new Datastore({ fileName: 'asyncStorageKey', autoload: true });

but when i reload or reopen app, data will be gone not thing to be saved.
I tried to check in AsyncStorage by key 'asyncStorageKey' and got null

**Comment by ZMChoo** [comment]
@huybq95 Hi, I have the same question here, have you solved this problem?
