### ISSUE TITLE
Unknown named module: 'util'

### ISSUE THREAD

**Issue by krishnaff** [antoniopresto/react-native-local-mongodb#3]
Hello, 

While using this on React Native 0.39.2, this is the error seen:

`
Unknown named module: 'util'
_require
    require.js:93
<unknown>
    model.js:8
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:123
_require
    require.js:107
<unknown>
    datastore.js:2
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:123
_require
    require.js:107
<unknown>
    index.js:1
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:123
_require
    require.js:107
<unknown>
    index.js:26
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:123
_require
    require.js:107
<unknown>
    index.android.js:2
loadModuleImplementation
    require.js:171
guardedLoadModule
    require.js:116
_require
    require.js:107
global code
    require-0.js:1
`

I guess, its because of 
`var Datastore = require('react-native-local-mongodb');`
But merely using import instead of require is not solving the problem. Any ideas how to make this plugin work please?

**Comment by WaffleStudios** [comment]
I have created a pull request #4 that addresses this issue.

**Comment by antoniopresto** [comment]
Thanks @CreatineDevelopment - Updated at npm.
