### ISSUE TITLE
Update objects by a list of id

### ISSUE THREAD

**Issue by huy-lv** [antoniopresto/react-native-local-mongodb#32]
Hi, is there any way to update a list of object by a list of their id. Code should be like
`db.update([{_id: aaa},{_id: bbb}, {_id: ccc}], {$set: {state: 'done'}})`

**Comment by antoniopresto** [comment]
try ["$in"](https://docs.mongodb.com/manual/reference/operator/query/in/#use-the-in-operator-to-match-values) with ``{multi: true}``
 db.update({_id: {$in: [...]}}, {$set: {state: 'done'}}, {multi: true})
