### ISSUE TITLE
Record create new one after call update

### ISSUE THREAD

**Issue by huy-lv** [antoniopresto/react-native-local-mongodb#33]
Hi, after diving into database file in data/data/host.exponent folder, i found that when i update a record by it's _id, db create a new one with new value (and keep same _id). This is the way you save db or it's a bug? If this is right way, when db got bigger, it should be have large size, isn't it?
![image](https://user-images.githubusercontent.com/7688070/38775706-4b8de400-40b3-11e8-8fe7-8ac9addcaa25.png)

**Comment by antoniopresto** [comment]
https://github.com/antoniopresto/react-native-local-mongodb#persistence
