### ISSUE TITLE
It works within redux?

### ISSUE THREAD

**Issue by federaimondi82** [antoniopresto/react-native-local-mongodb#38]
How I can import data from local-mongodb to my app using redux? Redux loads state in the first time,then it loads componentDidMount. Where I can use function to load data from local db?

**Comment by antoniopresto** [comment]
You can read the data from AsyncStorage. Please, note this: https://github.com/antoniopresto/react-native-local-mongodb#persistence

**Comment by antoniopresto** [comment]
Feel free to reopen
