### ISSUE TITLE
Import in react-native collections from MongoDB

### ISSUE THREAD

**Issue by jmlacruz** [antoniopresto/react-native-local-mongodb#43]
Hello, I'm trying to import a collection in react native from a collection exported from MongoDB. I'm not sure how to do this operation because when importing a collection from MongoDB, the resulting file is file .json.

The sentence in my project is as follows

~~~
var correlation = new Datastore({ filename: './data_store/correlation_backup.json', autoload: true });
~~~
Is it correct to import my collection like this?

Or should I do it this way?
~~~
var correlation = new Datastore({ filename: './data_store/correlation_backup.db', autoload: true });
~~~
Thank you very much for your time.

**Comment by antoniopresto** [comment]
Currently 'filename' is just a key that will be used in AsyncStorage, not a path to a real file.
https://github.com/antoniopresto/react-native-local-mongodb#creatingloading-a-database

**Comment by jmlacruz** [comment]
Thank you so much for responding so soon!

Ok! I get it. But is there any way to import a collection in react native with react-native-local-mongodb?

**Comment by antoniopresto** [comment]
there is currently no functionality to do this automatically; a good way to start would be to see how data is saved in AsyncStorage
