### ISSUE TITLE
Can't change setState 

### ISSUE THREAD

**Issue by sahimar90** [antoniopresto/react-native-local-mongodb#5]
`db.find({title:data.title}, function (err, result) {
			this.setState({colorBar:'red'});
		});`

the error this.setState is not a function.

**Comment by antoniopresto** [comment]
It is not related to this package.
You could also save a reference to `this`; or use arrow functions; or use `bind`;

Please, see: http://stackoverflow.com/questions/31045716/react-this-setstate-is-not-a-function

**Comment by amorenew** [comment]
`{ this.setState({colorBar:'red'}); }.bind(this)`

that's mean you bind the inner function
