### ISSUE TITLE
Where the data has been stored and how to save those data collection?

### ISSUE THREAD

**Issue by ZMChoo** [antoniopresto/react-native-local-mongodb#55]
Hi everyone, I want to develop an app to store some data in offline, did anyone know how to save data into a file or any temporary storage?  And one more thing, after insert data into Datastore, where can I found those data? I have tried to console `console.log(db)` it and check but it shows me this 

`Datastore {inMemoryOnly: false, autoload: false, timestampData: false, storage: Object, filename: "testingStorage1"…}
autoload
:
false
compareStrings
:
undefined
executor
:
Executor
filename
:
"testingStorage1"
inMemoryOnly
:
false
indexes
:
Object
persistence
:
Persistence
storage
:
Object
timestampData
:
false
ttlIndexes
:
Object
_events
:
Object
__proto__
:
EventEmitter`

**Comment by antoniopresto** [comment]
try `db.load()` or config with `autoload: true`
