### ISSUE TITLE
Is it possible to wait till document is received ?

### ISSUE THREAD

**Issue by yspanchal** [antoniopresto/react-native-local-mongodb#56]
Is it possible to wait till document is received in componentdidmount ?

Isfirst = () => {
     var value = undefined;
    dB.findOne({'isfirst': true}, function (err, doc){
         console.log(doc)
         value = doc
     })
     return value
}

Componentdidmount() {
    var value = this.Isfirst(); 
     console.log(value);
    }

**Comment by antoniopresto** [comment]
I did not understand your question, but you can use `db.findAsync`, which returns a promise

**Comment by yspanchal** [comment]
@antoniopresto can please give me an example of dB.findAsync how can I use it ? 

Thank you.
