### ISSUE TITLE
Cannot use persistence with the last version 

### ISSUE THREAD

**Issue by lironsher** [antoniopresto/react-native-local-mongodb#57]
With version 2.2.7 can't use persistence and the executor never turn to ready.

Nothing is working.

React-native version 0.56.1

**Comment by antoniopresto** [comment]
Please, can you confirm the version in node_modules?

**Comment by antoniopresto** [comment]
also, check the `async` package version that you are using

**Comment by lironsher** [comment]
The version in node_modules is 2.2.7
async version is 2.6.1

**Comment by antoniopresto** [comment]
I can't reproduce. looks like a package.lock issue. You can try delete your node_modules and install the 2.2.9 version

**Comment by lironsher** [comment]
I've upgraded to version 0.59.3 and its start working,
but now I get the AsyncStorage warning

**Comment by antoniopresto** [comment]
I had some problems upgrading to the community version of asyncStorage, I will not be able to upgrade for a while. You can pass a custom storage in the DataStore config.
see: https://github.com/antoniopresto/react-native-local-mongodb#using-a-custom-storage
