### ISSUE TITLE
Error: Couldn't read row 0, col 0 from CursorWindow.

### ISSUE THREAD

**Issue by gvmarvelos** [antoniopresto/react-native-local-mongodb#58]
Hello, I am trying to insert a large amount of data, using "update", with the parameters {uperset: true}, however it is giving the following error:

Error: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.

**Comment by antoniopresto** [comment]
please, see https://github.com/antoniopresto/react-native-local-mongodb/issues/52

**Comment by antoniopresto** [comment]
also: https://github.com/antoniopresto/react-native-local-mongodb/issues/42#issuecomment-432898339
