### ISSUE TITLE
AsyncStorage Support in React Native >= v0.59

### ISSUE THREAD

**Issue by chxmbley** [antoniopresto/react-native-local-mongodb#59]
Per [React Native's changelog](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#deprecated), AsyncStorage is being removed from the core RN package and extracted to [@react-native-community/async-storage](https://github.com/react-native-community/react-native-async-storage).

Using this library in version >= 0.59 causes a warning to appear in dev mode, reading:

```C:\Users\FlowDev\Desktop\LocalStorage\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:2326 Warning: Async Storage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/async-storage' instead of 'react-native'. See https://github.com/react-native-community/react-native-async-storage```

**Comment by chxmbley** [comment]
Looks like this was already [merged into master](https://github.com/antoniopresto/react-native-local-mongodb/pull/53)

**Comment by antoniopresto** [comment]
I have not been able to run on a real device, so I need to [ rollback the package for now.](https://github.com/antoniopresto/react-native-local-mongodb/pull/53#issuecomment-480344000) However, it is possible to [pass the new asyncStorage lib ](https://github.com/antoniopresto/react-native-local-mongodb#using-a-custom-storage)as a parameter.

**Comment by tex0l** [comment]
Any news on this? @antoniopresto

**Comment by antoniopresto** [comment]
https://github.com/antoniopresto/react-native-local-mongodb/commit/b5955beba169fe636c042dab1a0f0e74cfecd1de#diff-b8b299a0e1fb5c6b8af2005882604ba564e358b3aa92aae744e1e67756469418L42
