### ISSUE TITLE
Is it possible to select or filter data in different data collection?

### ISSUE THREAD

**Issue by ZMChoo** [antoniopresto/react-native-local-mongodb#60]
Hi, I'm a newbie in react native, for my question, is it possible to select the different collection(not sure is it datastore's filename in here) to access? For example, I have a filename called Storage A and Storage B, so when I load the database, how can I choose which database should be loaded?
` 
   db.loadDatabase(function (err, Storage A) {   
 // Callback is optional
}
`
I'm not sure this is the correct way or not?

**Comment by antoniopresto** [comment]
tou should create one db at a time and then use each one independently
