### ISSUE TITLE
Different Collection in Local DB

### ISSUE THREAD

**Issue by emannick** [antoniopresto/react-native-local-mongodb#61]
Hi, Is it possible to create different collections of data with different names? Right now DB is Initialized by 
var Datastore = require('react-native-local-mongodb'),
db = new Datastore({ filename: 'xyz'  });
If I want to use different collection how should I do that?

**Comment by antoniopresto** [comment]
> One datastore is the equivalent of a MongoDB collection
https://github.com/antoniopresto/react-native-local-mongodb#creatingloading-a-database

Of course you can create multiple datastores if you need
