### ISSUE TITLE
Options in typings.d.ts missing storage property

### ISSUE THREAD

**Issue by nuvolarmobileteam** [antoniopresto/react-native-local-mongodb#63]
I'm trying to specify the storage option when creating a new Datastore and I can not find the it under options. Would it be possible it is missing? If so I could create a PR.

Cheers

**Comment by antoniopresto** [comment]
its missing. send the PR, please :)
this can help you: https://github.com/react-native-community/react-native-async-storage/blob/67ae214ad5caebc83bb21e659e898924cb27fe6e/types/index.d.ts#L19
