### ISSUE TITLE
Support for compound indexes? [Enhancement]

### ISSUE THREAD

**Issue by jwh-hutchison** [antoniopresto/react-native-local-mongodb#73]
There doesn't seem to be support for compound indexes in this library so it's impossible to add unique constraints that are made up of multiple fields. This would be very useful to have, are there any plans for it to be added?
https://www.mongodb.com/docs/manual/core/index-compound/

**Comment by antoniopresto** [comment]
Hi!  No plans to add new features :(

**Comment by jwh-hutchison** [comment]
>
