### ISSUE TITLE
Event emitter for db events?

### ISSUE THREAD

**Issue by JulianKingman** [antoniopresto/react-native-local-mongodb#8]
What do you think about having events for db events, like updates/inserts/removals? It would be handy for updating the UI and other purposes.

**Comment by adjustit** [comment]
I personally use eventemitter2 (https://github.com/asyncly/EventEmitter2) for this purpose. Integrating it isn't particularly tricky, just have your emit event inside of the resulting function from any DB event as a callback. Works pretty nicely for the purpose and fairly lightweight.

**Comment by ashrithks** [comment]
You can use this to emit events, https://www.npmjs.com/package/react-native-event-listeners
