### ISSUE TITLE
Possible unhandled promise rejection (Row too big to fit into CursorWindow)

### ISSUE THREAD

**Issue by xh-lin** [antoniopresto/react-native-local-mongodb#81]
Hi, I'm getting this console warning, does anyone know why and how to resolve it?

![image](https://github.com/antoniopresto/react-native-local-mongodb/assets/55850802/ba834278-3396-4b37-8059-717e84602bb2)

my code:
```
  const itemsPromises = [];

  for (const [itemId, item] of pediaEx.items) {
    itemsPromises.push(
      itemsDb.insertAsync({
        key: itemId,
        val: item,
      }),
    );
  }

  await Promise.all(itemsPromises).then((docs) => {
    console.log(`items added ${docs.length} docs`);
  });
```

**Comment by antoniopresto** [comment]
`Row too big to fit into CursorWindow` is an error on Android's side. The best I can tell is that you can change the storage used.

**Comment by antoniopresto** [comment]
@xh-lin, maybe the promises are throwing before `await Promise.all...`.

Try:
```ts
await Promise.all(
  pediaEx.items.map(async ([itemId, item]) => {
    return itemsDb.insertAsync({
      key: itemId,
      val: item,
    });
  }),
).then((docs) => {
  console.log(`items added ${docs.length} docs`);
});

```

**Comment by antoniopresto** [comment]
...It might be better to use `Promise.allSettled`
